"""Real, public company domains used as Clay-eligible seed accounts.

Only company-level facts that are public (name, website domain, a broad industry
bucket, HQ country) live here. Every CONTACT in this project is synthetic.

Industry values use the project's 12-bucket taxonomy (see INDUSTRY_BUCKETS).
They are a rough seed value; Clay enrichment is the source of truth.
"""

INDUSTRY_BUCKETS = [
    "Software",
    "Data & Analytics",
    "Cybersecurity",
    "Fintech",
    "Healthcare",
    "Marketing Tech",
    "Sales Tech",
    "HR Tech",
    "E-commerce & Retail",
    "Logistics",
    "Developer Tools",
    "Media",
]

# (company_name, domain, industry_bucket, hq_country)
REAL_COMPANIES: list[tuple[str, str, str, str]] = [
    # Data & Analytics
    ("Snowflake", "snowflake.com", "Data & Analytics", "US"),
    ("Databricks", "databricks.com", "Data & Analytics", "US"),
    ("Fivetran", "fivetran.com", "Data & Analytics", "US"),
    ("dbt Labs", "getdbt.com", "Data & Analytics", "US"),
    ("Airbyte", "airbyte.com", "Data & Analytics", "US"),
    ("Hex", "hex.tech", "Data & Analytics", "US"),
    ("Sigma Computing", "sigmacomputing.com", "Data & Analytics", "US"),
    ("ThoughtSpot", "thoughtspot.com", "Data & Analytics", "US"),
    ("Monte Carlo", "montecarlodata.com", "Data & Analytics", "US"),
    ("Census", "getcensus.com", "Data & Analytics", "US"),
    ("Hightouch", "hightouch.com", "Data & Analytics", "US"),
    ("Amplitude", "amplitude.com", "Data & Analytics", "US"),
    ("Mixpanel", "mixpanel.com", "Data & Analytics", "US"),
    ("Heap", "heap.io", "Data & Analytics", "US"),
    ("Alation", "alation.com", "Data & Analytics", "US"),
    ("Collibra", "collibra.com", "Data & Analytics", "BE"),
    ("Starburst", "starburst.io", "Data & Analytics", "US"),
    ("Cockroach Labs", "cockroachlabs.com", "Data & Analytics", "US"),
    ("MongoDB", "mongodb.com", "Data & Analytics", "US"),
    ("Confluent", "confluent.io", "Data & Analytics", "US"),
    # Software
    ("Atlassian", "atlassian.com", "Software", "AU"),
    ("Asana", "asana.com", "Software", "US"),
    ("Notion", "notion.so", "Software", "US"),
    ("Airtable", "airtable.com", "Software", "US"),
    ("Monday.com", "monday.com", "Software", "IL"),
    ("Smartsheet", "smartsheet.com", "Software", "US"),
    ("Miro", "miro.com", "Software", "US"),
    ("Figma", "figma.com", "Software", "US"),
    ("Canva", "canva.com", "Software", "AU"),
    ("Dropbox", "dropbox.com", "Software", "US"),
    ("Box", "box.com", "Software", "US"),
    ("Zoom", "zoom.us", "Software", "US"),
    ("Slack", "slack.com", "Software", "US"),
    ("Loom", "loom.com", "Software", "US"),
    ("Calendly", "calendly.com", "Software", "US"),
    ("DocuSign", "docusign.com", "Software", "US"),
    ("ServiceNow", "servicenow.com", "Software", "US"),
    ("Workato", "workato.com", "Software", "US"),
    ("Zapier", "zapier.com", "Software", "US"),
    ("Retool", "retool.com", "Software", "US"),
    # Developer Tools
    ("GitLab", "gitlab.com", "Developer Tools", "US"),
    ("Vercel", "vercel.com", "Developer Tools", "US"),
    ("Netlify", "netlify.com", "Developer Tools", "US"),
    ("Postman", "postman.com", "Developer Tools", "US"),
    ("Sentry", "sentry.io", "Developer Tools", "US"),
    ("Datadog", "datadoghq.com", "Developer Tools", "US"),
    ("PagerDuty", "pagerduty.com", "Developer Tools", "US"),
    ("HashiCorp", "hashicorp.com", "Developer Tools", "US"),
    ("JetBrains", "jetbrains.com", "Developer Tools", "CZ"),
    ("LaunchDarkly", "launchdarkly.com", "Developer Tools", "US"),
    # Cybersecurity
    ("CrowdStrike", "crowdstrike.com", "Cybersecurity", "US"),
    ("Okta", "okta.com", "Cybersecurity", "US"),
    ("Cloudflare", "cloudflare.com", "Cybersecurity", "US"),
    ("Zscaler", "zscaler.com", "Cybersecurity", "US"),
    ("SentinelOne", "sentinelone.com", "Cybersecurity", "US"),
    ("Snyk", "snyk.io", "Cybersecurity", "US"),
    ("1Password", "1password.com", "Cybersecurity", "CA"),
    ("Vanta", "vanta.com", "Cybersecurity", "US"),
    ("Drata", "drata.com", "Cybersecurity", "US"),
    ("Rapid7", "rapid7.com", "Cybersecurity", "US"),
    # Fintech
    ("Stripe", "stripe.com", "Fintech", "US"),
    ("Plaid", "plaid.com", "Fintech", "US"),
    ("Brex", "brex.com", "Fintech", "US"),
    ("Ramp", "ramp.com", "Fintech", "US"),
    ("Chime", "chime.com", "Fintech", "US"),
    ("Affirm", "affirm.com", "Fintech", "US"),
    ("Marqeta", "marqeta.com", "Fintech", "US"),
    ("Mercury", "mercury.com", "Fintech", "US"),
    ("Bill.com", "bill.com", "Fintech", "US"),
    ("Wise", "wise.com", "Fintech", "GB"),
    # Healthcare
    ("Oscar Health", "hioscar.com", "Healthcare", "US"),
    ("Teladoc Health", "teladochealth.com", "Healthcare", "US"),
    ("Hinge Health", "hingehealth.com", "Healthcare", "US"),
    ("Zocdoc", "zocdoc.com", "Healthcare", "US"),
    ("Doximity", "doximity.com", "Healthcare", "US"),
    ("Tempus", "tempus.com", "Healthcare", "US"),
    ("Flatiron Health", "flatiron.com", "Healthcare", "US"),
    ("Veeva Systems", "veeva.com", "Healthcare", "US"),
    ("Komodo Health", "komodohealth.com", "Healthcare", "US"),
    ("Athenahealth", "athenahealth.com", "Healthcare", "US"),
    # Marketing Tech
    ("HubSpot", "hubspot.com", "Marketing Tech", "US"),
    ("Braze", "braze.com", "Marketing Tech", "US"),
    ("Klaviyo", "klaviyo.com", "Marketing Tech", "US"),
    ("Iterable", "iterable.com", "Marketing Tech", "US"),
    ("Semrush", "semrush.com", "Marketing Tech", "US"),
    ("Sprout Social", "sproutsocial.com", "Marketing Tech", "US"),
    ("Hootsuite", "hootsuite.com", "Marketing Tech", "CA"),
    ("Mailchimp", "mailchimp.com", "Marketing Tech", "US"),
    ("Webflow", "webflow.com", "Marketing Tech", "US"),
    ("Contentful", "contentful.com", "Marketing Tech", "DE"),
    # Sales Tech
    ("Salesforce", "salesforce.com", "Sales Tech", "US"),
    ("Gong", "gong.io", "Sales Tech", "US"),
    ("Outreach", "outreach.io", "Sales Tech", "US"),
    ("Salesloft", "salesloft.com", "Sales Tech", "US"),
    ("Apollo.io", "apollo.io", "Sales Tech", "US"),
    ("ZoomInfo", "zoominfo.com", "Sales Tech", "US"),
    ("Clari", "clari.com", "Sales Tech", "US"),
    ("Pipedrive", "pipedrive.com", "Sales Tech", "US"),
    # HR Tech
    ("Rippling", "rippling.com", "HR Tech", "US"),
    ("Gusto", "gusto.com", "HR Tech", "US"),
    ("Deel", "deel.com", "HR Tech", "US"),
    ("Lattice", "lattice.com", "HR Tech", "US"),
    ("Greenhouse", "greenhouse.io", "HR Tech", "US"),
    ("Lever", "lever.co", "HR Tech", "US"),
    ("BambooHR", "bamboohr.com", "HR Tech", "US"),
    ("Workday", "workday.com", "HR Tech", "US"),
    # E-commerce & Retail
    ("Shopify", "shopify.com", "E-commerce & Retail", "CA"),
    ("Instacart", "instacart.com", "E-commerce & Retail", "US"),
    ("Etsy", "etsy.com", "E-commerce & Retail", "US"),
    ("Wayfair", "wayfair.com", "E-commerce & Retail", "US"),
    ("Chewy", "chewy.com", "E-commerce & Retail", "US"),
    ("BigCommerce", "bigcommerce.com", "E-commerce & Retail", "US"),
    # Logistics
    ("Flexport", "flexport.com", "Logistics", "US"),
    ("Samsara", "samsara.com", "Logistics", "US"),
    ("project44", "project44.com", "Logistics", "US"),
    ("ShipBob", "shipbob.com", "Logistics", "US"),
    # Media
    ("Spotify", "spotify.com", "Media", "SE"),
    ("Substack", "substack.com", "Media", "US"),
]
